config_version: "1.0.0"

repo:
  url: https://github.com/johnkerl/miller
  branch: main

execution_plan:
  mode: tests
  compile_commands:
    - make
  granularity: commits
  test_command: make check
  num_runs: 3
  num_repeats: 1
  randomize_tasks: true
  batch_size: 30
  num_commits: 8000
  search_strategy: pruned_endpoint_segmentation
limits:
  temperature_safe_limit: 65000

regression_detection:
  min_commits_before: 0

tracked_file_extensions:
  - go # Go source code
  - mod # Go module definition (go.mod)
  - sum # Go module checksum (go.sum)
  - yaml # Common for config (esp. CI/CD)
  - yml # Alternative YAML
  - json # Common for config, APIs, and tests
  - toml # Sometimes used for configuration (e.g., go-task)
  - env # Environment variables (dotenv pattern)
  - sh # Build/test scripts
  - Makefile # Build scripts

cpu_thermal_file: /sys/class/hwmon/hwmon5/temp1_input
